### ISSUE TITLE
Non-ISO-Latin/ASCII character sets

### ISSUE THREAD

**Issue by simonatdrg** [scoder/acora#7]
I would like to use acora for searching Japanese text for keywords. It claims to be Unicode compliant but I'm wondering if there has been any experience or reports of bugs when using it with  non-ASCII /ISO-Latin strings ?
Also, +1 on improving the speed of construction as we have a dictionary of 77K Japanese keywords to be loaded.

**Comment by scoder** [comment]
Did you actually try it? Unicode input should just work, either by parsing
from a (Unicode) text file, or by encoding the keywords in the encoding of
the file and parsing it as byte strings. Whatever suites you better.

Can I close this ticket, or is there an actual problem?

**Comment by aolieman** [comment]
FYI, I've done some (limited) tests with unicode keywords and input and encountered no issues. There should be nothing special about Japanese characters in unicode, so if you encounter any bugs that would be interesting.

**Comment by scoder** [comment]
closing as "not an issue"
